# Generated by Django 2.1 on 2018-08-27 19:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180828_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.Student.get_photo, verbose_name='照片'),
        ),
    ]
